# Generated by Django 3.2 on 2021-04-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_secondchallenge', '0005_auto_20210419_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_amount', models.FloatField()),
                ('attachment', models.TextField(blank=True, max_length=200)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depositor', to='transaction_secondchallenge.account')),
            ],
        ),
    ]
